apiVersion: v1
kind: Pod
metadata:
  name: retagger
spec:
  containers:
  - name: retagger 
    image: gcr.io/gcp-runtimes/retagger:latest
    volumeMounts:
    - name: git-volume
      mountPath: /data
    - name: retagger-secret
      mountPath: /secret
    args: ["/data/[PATH TO JSON FILE IN YOUR GIT REPOSITORY]"]
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/retagger_secret.json
  volumes:
  - name: git-volume
    gitRepo:
      repository: [LINK TO YOUR GIT REPOSITORY]
  - name: retagger-secret
    secret:
      secretName: retagger-secret