package(default_visibility = ["//visibility:public"])

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_library",
)

go_library(
    name = "go_default_library",
    srcs = ["versions.go"],
    deps = ["@in_gopkg_yaml_v2//:go_default_library"],
)
