#Pull and tag a simple docker image for retagger e2e test
steps:
  - name:  'gcr.io/cloud-builders/docker'
    args: ['pull', 'registry.k8s.io/pause:3.8']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'registry.k8s.io/pause:3.8', 'gcr.io/gcp-runtimes/reconciler-e2etest:initial']
images: ['gcr.io/gcp-runtimes/reconciler-e2etest:initial']
