steps:
#Build the par files with bazel
  - name:  'gcr.io/cloud-builders/bazel'
    args: ['build', 'reconciletags:reconciletags.par']
  - name:  'gcr.io/cloud-builders/bazel'
    args: ['build', 'reconciletags:config_integrity.par']
  - name:  'gcr.io/cloud-builders/bazel'
    args: ['build', 'reconciletags:data_integrity.par']
#Copy par files into commit SHA bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/reconciletags/reconciletags.par', 'gs://reconciletags/$COMMIT_SHA/']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/reconciletags/config_integrity.par', 'gs://reconciletags/$COMMIT_SHA/']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/reconciletags/data_integrity.par', 'gs://reconciletags/$COMMIT_SHA/']
#Copy par files into 'latest' bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://reconciletags/$COMMIT_SHA/*', 'gs://reconciletags/latest/']
