steps:
# Build the binary with bazel
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['run', '//structure_tests:structure_test_image']
# Tag the built image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'bazel/structure_tests:structure_test_image', 'gcr.io/gcp-runtimes/structure-test-v2:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/bazel'
    args: ['build', '//structure_tests:go_default_test']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'bazel-bin/structure_tests/go_default_test', 'gs://structure-test/$COMMIT_SHA/structure-test']

images: ['gcr.io/gcp-runtimes/structure-test:$COMMIT_SHA']
