steps:
- name: 'gcr.io/gcp-runtimes/aspnetcorebuild:latest'
  args:
    - '--version-map'
    - '1.0.15=gcr.io/google-appengine/aspnetcore:1.0.15'
    - '1.1.12=gcr.io/google-appengine/aspnetcore:1.1.12'
    - '2.0.9=gcr.io/google-appengine/aspnetcore:2.0.9'
    - '2.1.9=gcr.io/google-appengine/aspnetcore:2.1.9'
    - '2.2.3=gcr.io/google-appengine/aspnetcore:2.2.3'
- name: 'gcr.io/kaniko-project/executor:v0.4.0'
  args: ['--destination=$_OUTPUT_IMAGE']
