load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["utils.go"],
    visibility = ["//visibility:public"],
    deps = ["//structure_tests/types/unversioned:go_default_library"],
)
